version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: memories-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - ${DATABASE_URL}
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: /wait-for-it.sh -s db:3306 -- go run main.go
